version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl http://localhost:8080/v1/health"
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s