version: "2.8"
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: password

  uploadservice:
    build: .
    depends_on:
      - mongo
    healthcheck:
      test: [ "CMD" ,"curl", "-f","http://localhost:8001/v1/health" ]
      interval: 5s
      retries: 10
      start_period: 5s
      timeout: 10s
  nginx_server:
    image: nginx:1.23.3-alpine
    depends_on:
      uploadservice:
        condition: service_healthy
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - "8080:8080"

